name = "AIMEE"
prefix = "AIMEE"
author = "johnb43"
template = "cba"
mainprefix = "x"
files = [
    "mod.cpp",
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
]
folder_optionals = true
sig_version = 3
